apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.django.name }}-service
spec:
  type: {{ .Values.django.service.type }}
  selector:
    app: {{ .Values.django.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.django.service.port }}
      targetPort: {{ .Values.django.service.port }}
      nodePort: {{ .Values.django.service.nodePort }}

