apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.django.name }}-config
  labels:
    app: {{ .Values.django.name }}
data:
  DB_HOST: {{ .Values.db.host }}
  DB_NAME: {{ .Values.db.name }}
  DB_USER: {{ .Values.db.user }}
  DB_PASS: {{ .Values.db.password }}
