apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.host }}
spec:
  type: {{ .Values.postgresql.service.type }}
  selector:
    app: {{ .Values.postgresql.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
