apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgresql.pv.name }}
  capacity:
    storage: {{ .Values.postgresql.pv.capacity.storage }}
  volumeMode: {{ .Values.postgresql.pv.volumeMode }}
  persistentVolumeReclaimPolicy: {{ .Values.postgresql.pv.persistentVolumeReclaimPolicy }}
  accessModes:
    - {{ .Values.postgresql.pv.accessMode }}
  nfs:
    server: {{ .Values.postgresql.pv.nfs.server }}
    path: {{ .Values.postgresql.pv.nfs.path }}
